version: '0.1.{build}'
init:
- git config --global core.autocrlf true
branches:
  only:
  - master
  - /^release\/.*$/
  - /^(.*\/)?ci-.*$/
build_script:
- cmd: .\package.cmd
- sh: ./package.sh
clone_depth: 1
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  AZBRIDGE_TEST_CXNSTRING:
    secure: DLwQwbX0CCtVlezqK0rPcIgnxFofTos/c3UMLTGSIWdHFwO9YHIU8a6fbxVaH5sFP+MS/ELLP66C4KVY8KwAf2EkF5ZgNm8624d1ERwN6xNCQbIVprzXw0TfgWRdIp76/07R1BnGZ/+lawAieosU9v/r6L8ibaoWB3f+mfOAgAz+dkm+azytP9A3NgrbKhr6LiRirVTrzz4+JgVDrwTgKA==
deploy: 'off'
test_script:
  cmd: .\verify_build.cmd
  sh: .\verify_build.sh
image: 
  - Visual Studio 2017
  - Ubuntu
artifacts:
  - path: 'artifacts\build\**\*.tar.gz'
  - path: 'artifacts\build\**\*.zip'
  - path: 'artifacts\build\**\*.deb'
  - path: 'artifacts\build\**\*.rpm'
  - path: 'artifacts\build\**\*.msi'