version: '{build}'
init:
- git config --global core.autocrlf true
branches:
  only:
  - master
  - /^release\/.*$/
  - /^(.*\/)?ci-.*$/
dotnet_csproj:
  patch: true
  file: 'version.props'
build_script:
- ps: .\run.ps1
clone_depth: 1
environment:
  BUILD_NUMBER : '{build}'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  AZBRIDGE_TEST_CXNSTRING:
    secure: DLwQwbX0CCtVlezqK0rPcIgnxFofTos/c3UMLTGSIWdHFwO9YHIU8a6fbxVaH5sFP+MS/ELLP66C4KVY8KwAf2EkF5ZgNm8624d1ERwN6xNCQbIVprzXw0TfgWRdIp76/07R1BnGZ/+lawAieosU9v/r6L8ibaoWB3f+mfOAgAz+dkm+azytP9A3NgrbKhr6LiRirVTrzz4+JgVDrwTgKA==
test: 'auto'
deploy: 'off'
os: Visual Studio 2017
