language: csharp
sudo: false
dist: trusty
env:
  global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  - DOTNET_CLI_TELEMETRY_OPTOUT: 1
  matrix:
    secure: FXyPKpK7oCiEfkeJfJtruRgA1EvR4xiNusSemcytb+QsVPrijJx06985MEftsvNCH8pXhqFWyrFlDlR527/kxSLYDdzX+08ZmoCesxUMLKEPdtcLTb9Fa0xKcCf4Cxuw8+QeWW/gMvVqfpiQXwV1/VhjiSTgChwETW0neRX/nw91tDe1VM2pb5Hl8p+Cb1uabvSAsNYch2WTa/E4Qjf7v0vhzuLZvyxkgUHHHflUilJmY+WPh82y6URw3Bp3EYNOLnG64pdF0ZV3PJUFKo/mqLhoZBpMGXD5nt04t0bKG1AcFGAnZLHXahFcyRoUNxSavV4J1T4B0tjN5v8OmHzdbgocljSGT/MeLwYbCO0FU9lhEKqqdxQJSs9Ax1lJ9QpSvyoAO5SJTInVcMck/P+9n9vf1Z7g5xPxo8XCWzb//Z60QxAPP0tasjNoUWAy3vJAVuRxNubHBC+S8OEbFPkXA996rHL/n6OtPAk3FouTJaMLE/vqs/Yo6eSFlVXTea7NJopkTK9opd3pUxzO9Lu4XR/AlaoaGF6/Ejj/oA913ZVrju5oYJ0a0wQSCUX2ZHebfQeV/ErGkH1Ckmcuul0Q1PB+0Z9jn6CFBkBtfvsp0OhJ0pUs6F0+lWuKgujQvsQzffBU1fW1uk3kqCo7n6jV/QRF3TFQu5FuOlAl71DWdq8=
mono: none
dotnet: 2.1.300
os:
- linux
- osx
osx_image: xcode8.2
addons:
  apt:
    packages:
    - libunwind8
branches:
  only:
  - master
  - "/^release\\/.*$/"
  - "/^(.*\\/)?ci-.*$/"
before_install:
- if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; ln -s
  /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  /usr/local/lib/; fi
script:
- "./build.sh"
